import fs from 'node:fs';

const html = fs.readFileSync('app/preferences.html', 'utf-8');
const escaped = JSON.stringify(html);

const output = `// Auto-generated by embed-html.mjs — do not edit\nexport const preferencesHtml = ${escaped};\n`;

fs.writeFileSync('app/src/preferencesHtml.ts', output);
console.log('Embedded preferences.html into preferencesHtml.ts');